Repository gentoo/gentoo, pull requests merged in 2023-05, with the labels that each got.

#31047 sci-libs/proj: drop 7.2.1-r1, 9.1.0-r1
  sci-libs/proj/Manifest
  sci-libs/proj/metadata.xml
  sci-libs/proj/proj-7.2.1-r1.ebuild
  sci-libs/proj/proj-9.1.0-r1.ebuild
Labels: assigned, no bug found, noci

#31046 net-libs/libproxy: Version bump to 0.5.0
  net-libs/libproxy/Manifest
  net-libs/libproxy/files/0.5.0-Guard-PxManager-test-with-pacrunner-duktape-option-2.patch
  net-libs/libproxy/libproxy-0.5.0.ebuild
Labels: assigned, bug linked

#31134 dev-libs/libclc: Enable USE=spirv by default
  dev-libs/libclc/libclc-15.0.7.ebuild
  dev-libs/libclc/libclc-16.0.3.ebuild
  dev-libs/libclc/libclc-16.0.4.ebuild
  dev-libs/libclc/libclc-16.0.5.9999.ebuild
  dev-libs/libclc/libclc-17.0.0.9999.ebuild
  dev-libs/libclc/libclc-17.0.0_pre20230502.ebuild
  dev-libs/libclc/libclc-17.0.0_pre20230512.ebuild
  dev-libs/libclc/libclc-17.0.0_pre20230520.ebuild
Labels: assigned, no bug found

#31140 games-puzzle/ltris: Install highscore file in /var/games
  games-puzzle/ltris/ltris-1.0.19-r2.ebuild
Labels: assigned, bug linked
