Repository gentoo/gentoo, pull requests merged in 2023-02, with the labels that each got.

#29436 app-office/scribus: Add python3_11, fix memleak, fix dashed lines
  app-office/scribus/Manifest
  app-office/scribus/files/scribus-1.5.8-cmake.patch
  app-office/scribus/scribus-1.5.8-r5.ebuild
Labels: assigned, bug linked, noci

#29437 media-libs/lensfun: add 0.3.4_rc1, py311
  media-libs/lensfun/Manifest
  media-libs/lensfun/lensfun-0.3.4_rc1.ebuild
Labels: assigned, no bug found, noci

#29666 profiles: move USE="fortran openmp" from default/linux to releases/17.0
  profiles/default/linux/make.defaults
  profiles/releases/17.0/make.defaults
Labels: need assignment, bug linked
