Repository gentoo/gentoo, pull requests merged in 2023-06, with the labels that each got.

#31378 app-crypt/gpgme: drop 1.17.1-r2, 1.18.0-r2, 1.19.0
  app-crypt/gpgme/Manifest
  app-crypt/gpgme/gpgme-1.17.1-r2.ebuild
  app-crypt/gpgme/gpgme-1.18.0-r2.ebuild
  app-crypt/gpgme/gpgme-1.19.0.ebuild
Labels: assigned, no bug found, noci

#31579 profiles/base: change to PHP_TARGETS="php8-1"
  profiles/base/make.defaults
Labels: need assignment, bug linked, priority-ci

#31651 dev-util/perf: Many dependency fixes
  dev-util/perf/perf-6.3-r1.ebuild
Labels: assigned, bug linked
