Repository gentoo/gentoo, pull requests merged in 2024-09, with the labels that each got.

#38392 kernel-build.eclass: handle CTF if enabled
  eclass/kernel-build.eclass
Labels: need assignment

#38582 x11-libs/libdrm: Add IUSE=doc to control man pages
  x11-libs/libdrm/libdrm-2.4.122-r1.ebuild
  x11-libs/libdrm/libdrm-2.4.123-r1.ebuild
  x11-libs/libdrm/libdrm-9999.ebuild
Labels: assigned, no bug found

#38352 REQUIRED_USE qt5 vs. qt6 conflicts are terrible and must be avoided
  media-libs/simage/simage-9999.ebuild
Labels: assigned, bug linked, noci
