Repository gentoo/gentoo, pull requests merged in 2025-05, with the labels that each got.

#41976 profiles: Mask kde-frameworks/kinit for removal
  profiles/package.mask
Labels: need assignment, noci

#42258 ssl-cert.eclass fixes
  eclass/ssl-cert.eclass
Labels: need assignment, bug linked

#42357 profiles: Mask sys-boot/vboot-utils for removal
  profiles/package.mask
Labels: need assignment, bug linked, noci
