Repository gentoo/gentoo, pull requests merged in 2025-03, with the labels that each got.

#40932 app-admin/setools: drop 4.4.4
  app-admin/setools/Manifest
  app-admin/setools/setools-4.4.4.ebuild
Labels: assigned, bug linked, noci, priority-ci

#40900 dev-build/muon: Add missing dev-util/gdbus-codegen test dep
  dev-build/muon/muon-0.4.0.ebuild
Labels: assigned, bug linked

#40983 Qt5-based, EAPI7Removal and other cleanup
  media-video/jellyfin-media-player/Manifest
  media-video/jellyfin-media-player/jellyfin-media-player-1.7.1-r1.ebuild
  media-video/jellyfin-media-player/jellyfin-media-player-1.8.1.ebuild
  media-video/jellyfin-media-player/jellyfin-media-player-1.9.0.ebuild
  media-video/jellyfin-media-player/jellyfin-media-player-1.9.1.ebuild
Labels: assigned, bug linked, noci, no assignee limit

#41225 Qt5 removal: media-gfx/opencsg: drop 1.5.1-r1, 1.6.0
  media-gfx/opencsg/Manifest
  media-gfx/opencsg/files/opencsg-1.4.2-includepath.patch
  media-gfx/opencsg/files/opencsg-1.6.0-includepath.patch
  media-gfx/opencsg/opencsg-1.5.1-r1.ebuild
  media-gfx/opencsg/opencsg-1.6.0.ebuild
Labels: assigned, no bug found, noci
