Repository gentoo/gentoo, pull requests merged in 2025-07, with the labels that each got.

#42818 dev-build/bmake: add 20250618
  dev-build/bmake/Manifest
  dev-build/bmake/bmake-20250618.ebuild
  dev-build/bmake/files/bmake-20250618-lua-test.patch
Labels: assigned, self-maintained, bug linked

#42949 Qt5-- continued
  gnome-extra/pch-session/Manifest
  gnome-extra/pch-session/pch-session-45.0.ebuild
  gnome-extra/pch-session/pch-session-47.0.ebuild
Labels: assigned, no bug found, noci

#43086 dev-libs/openssl: set LD_LIBRARY_PATH when calling openssl
  dev-libs/openssl/openssl-3.0.16.ebuild
  dev-libs/openssl/openssl-3.0.17.ebuild
  dev-libs/openssl/openssl-3.0.9999.ebuild
  dev-libs/openssl/openssl-3.1.8.ebuild
  dev-libs/openssl/openssl-3.1.9999.ebuild
  dev-libs/openssl/openssl-3.2.4.ebuild
  dev-libs/openssl/openssl-3.2.5.ebuild
  dev-libs/openssl/openssl-3.2.9999.ebuild
  dev-libs/openssl/openssl-3.3.3.ebuild
  dev-libs/openssl/openssl-3.3.4.ebuild
  dev-libs/openssl/openssl-3.3.9999.ebuild
  dev-libs/openssl/openssl-3.4.1.ebuild
  dev-libs/openssl/openssl-3.4.2.ebuild
  dev-libs/openssl/openssl-3.4.9999.ebuild
  dev-libs/openssl/openssl-3.5.0.ebuild
  dev-libs/openssl/openssl-3.5.1.ebuild
  dev-libs/openssl/openssl-3.5.9999.ebuild
Labels: assigned, bug linked
